default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-watch-list_development

test:
  <<: *default
  database: rails-watch-list_test

production:
  <<: *default
  database: RAILS_WATCH_LIST_production
  username: RAILS_WATCH_LIST
  password: <%= ENV['RAILS_WATCH_LIST_DATABASE_PASSWORD'] %>
